"""Generate the diagram stylesheet.

Colours are computed here rather than baked into the SVG so that one rendered
diagram serves both the light and dark themes, and so the palette can be
changed without recapturing or re-rendering anything.

Two channels, kept strictly separate:

* **hue = phase.** Which part of the run a hook belongs to.
* **lightness = frequency.** How often the hook was called, on a log scale
  bucketed into discrete steps.

Nothing else uses colour. In particular, changes between pytest versions do
*not* get a colour: presence changes are answerable with ctrl-F, and ordering
changes - the ones ctrl-F cannot help with - are surfaced by grouping instead,
which is where they belong.
"""

from __future__ import annotations

from .dot import PHASE_HUES, SHADE_STEPS

#: How far the palest and darkest fills travel from the page background toward
#: the hue. Capped well short of full saturation so body text stays readable on
#: the darkest step without needing a second text colour.
MAX_TINT_LIGHT = 0.42
MAX_TINT_DARK = 0.52

LIGHT_BACKGROUND = (255, 255, 255)
DARK_BACKGROUND = (30, 33, 41)


def _rgb(colour: str) -> tuple[int, int, int]:
    return tuple(int(colour[i : i + 2], 16) for i in (1, 3, 5))  # type: ignore[return-value]


def _mix(hue: tuple[int, int, int], background: tuple[int, int, int], strength: float) -> str:
    channels = (round(bg + (h - bg) * strength) for h, bg in zip(hue, background, strict=True))
    return "#{:02X}{:02X}{:02X}".format(*channels)


def _fills(hue: str, background: tuple[int, int, int], ceiling: float) -> list[str]:
    rgb = _rgb(hue)
    return [
        _mix(rgb, background, (step / max(SHADE_STEPS - 1, 1)) * ceiling)
        for step in range(SHADE_STEPS)
    ]


def _phase_rules(background: tuple[int, int, int], ceiling: float, prefix: str = "") -> str:
    lines = []
    for phase, hue in PHASE_HUES.items():
        for step, fill in enumerate(_fills(hue, background, ceiling)):
            lines.append(
                f"{prefix}.ha-diagram .ha-{phase}.ha-shade-{step} > path,\n"
                f"{prefix}.ha-diagram .ha-{phase}.ha-shade-{step} > polygon "
                f"{{ fill: {fill}; stroke: {hue}; }}"
            )
        lines.append(f"{prefix}.ha-diagram .ha-column.ha-{phase} > path {{ stroke: {hue}; }}")
        lines.append(f"{prefix}.ha-diagram .ha-column.ha-{phase} > text {{ fill: {hue}; }}")
    return "\n".join(lines)


BASE = """/* Diagrams are inlined SVG so their links stay clickable and CSS can theme
   them. Generated by pytest_hook_atlas.render.css - do not edit by hand. */
.ha-diagram {
  overflow-x: auto;
  margin: 1.2rem 0;
}
.ha-diagram svg {
  max-width: 100%;
  height: auto;
}
.ha-diagram text {
  fill: var(--md-default-fg-color);
}
/* the muted subtitle graphviz emits for hook semantics and repeat counts */
.ha-diagram text[fill="#8a8a8a"] {
  fill: var(--md-default-fg-color--light);
}
.ha-diagram .edge path {
  stroke: var(--md-default-fg-color--light);
  fill: none;
}
.ha-diagram .edge polygon {
  fill: var(--md-default-fg-color--light);
  stroke: var(--md-default-fg-color--light);
}
.ha-diagram a:hover text {
  text-decoration: underline;
}
.ha-diagram .ha-column > path {
  fill: none;
}
"""


def stylesheet() -> str:
    """The full diagram stylesheet, light and dark."""
    return "\n\n".join(
        [
            BASE,
            "/* light theme: hues tinted toward white */",
            _phase_rules(LIGHT_BACKGROUND, MAX_TINT_LIGHT),
            "/* dark theme: the same hues tinted toward the page background */",
            '[data-md-color-scheme="slate"] .ha-diagram .ha-column > path { fill: none; }',
            _phase_rules(DARK_BACKGROUND, MAX_TINT_DARK, prefix='[data-md-color-scheme="slate"] '),
            "",
        ]
    )
