"""Generate the diagram stylesheet.

Colours are computed here rather than baked into the SVG so one rendered
diagram serves both the light and dark themes, and so the palette can change
without recapturing or re-rendering anything.

Two channels, kept strictly separate:

* **hue = phase.** Which part of the run a hook belongs to.
* **lightness = frequency.** How often the hook was called, log-scaled and
  bucketed into discrete steps.

Nothing else uses colour. Changes between pytest versions deliberately do not:
presence changes are answerable with ctrl-F, and ordering changes - the ones
ctrl-F cannot help with - are surfaced by grouping instead.

**Contrast is computed, not eyeballed.** A hue that reads well on white is
usually invisible on the dark theme and vice versa: raw ``#DDCC77`` scores
1.6:1 on white, ``#332288`` scores 1.3:1 on the slate background. So every
colour used for text or strokes is pushed toward or away from the background
until it clears a WCAG target, per theme.
"""

from __future__ import annotations

from .dot import PHASE_HUES, SHADE_STEPS

#: How far the darkest fill travels from the page background toward the hue.
#: Capped so the muted subtitle text still clears 3:1 on the darkest step -
#: raising these is what made subtitles unreadable at 1.9:1.
MAX_TINT_LIGHT = 0.26
MAX_TINT_DARK = 0.34

#: WCAG AA for normal text; strokes and titles are held to the same bar.
TARGET_CONTRAST = 4.5

LIGHT_BACKGROUND = (255, 255, 255)
DARK_BACKGROUND = (30, 33, 41)

Rgb = tuple[int, int, int]


def _rgb(colour: str) -> Rgb:
    return tuple(int(colour[i : i + 2], 16) for i in (1, 3, 5))  # type: ignore[return-value]


def _hex(colour: Rgb) -> str:
    return "#{:02X}{:02X}{:02X}".format(*colour)


def _relative_luminance(colour: Rgb) -> float:
    def channel(value: int) -> float:
        srgb = value / 255
        return srgb / 12.92 if srgb <= 0.03928 else ((srgb + 0.055) / 1.055) ** 2.4

    red, green, blue = (channel(c) for c in colour)
    return 0.2126 * red + 0.7152 * green + 0.0722 * blue


def contrast(first: Rgb, second: Rgb) -> float:
    """WCAG contrast ratio, 1.0 (identical) to 21.0 (black on white)."""
    a, b = _relative_luminance(first), _relative_luminance(second)
    lighter, darker = max(a, b), min(a, b)
    return (lighter + 0.05) / (darker + 0.05)


def _mix(colour: Rgb, target: Rgb, strength: float) -> Rgb:
    return tuple(  # type: ignore[return-value]
        round(c + (t - c) * strength) for c, t in zip(colour, target, strict=True)
    )


def readable_on(hue: str, background: Rgb, target: float = TARGET_CONTRAST) -> str:
    """Push ``hue`` away from ``background`` until it clears ``target``.

    Darkens against a light background and lightens against a dark one, in
    small steps, so the result stays recognisably the same hue. Used for column
    titles and node borders, which are the elements that failed outright.
    """
    colour = _rgb(hue)
    extreme: Rgb = (0, 0, 0) if _relative_luminance(background) > 0.5 else (255, 255, 255)
    for step in range(21):
        candidate = _mix(colour, extreme, step * 0.05)
        if contrast(candidate, background) >= target:
            return _hex(candidate)
    return _hex(extreme)


def _fills(hue: str, background: Rgb, ceiling: float) -> list[str]:
    rgb = _rgb(hue)
    return [
        _hex(_mix(background, rgb, (step / max(SHADE_STEPS - 1, 1)) * ceiling))
        for step in range(SHADE_STEPS)
    ]


def _phase_rules(background: Rgb, ceiling: float, prefix: str = "") -> str:
    lines = []
    for phase, hue in PHASE_HUES.items():
        stroke = readable_on(hue, background, 3.0)
        title = readable_on(hue, background)
        for step, fill in enumerate(_fills(hue, background, ceiling)):
            # Descendant, not child. Graphviz wraps any shape carrying an
            # href in <g><a>, so the path is a grandchild - "> path" silently
            # matched nothing and every node kept its default grey fill.
            # Groups are siblings in Graphviz's output, never nested, so a
            # descendant selector cannot leak into neighbouring nodes.
            lines.append(
                f"{prefix}.ha-diagram .ha-{phase}.ha-shade-{step} path,\n"
                f"{prefix}.ha-diagram .ha-{phase}.ha-shade-{step} polygon "
                f"{{ fill: {fill}; stroke: {stroke}; }}"
            )
        lines.append(f"{prefix}.ha-diagram .ha-column.ha-{phase} path {{ stroke: {title}; }}")
        lines.append(f"{prefix}.ha-diagram .ha-column.ha-{phase} text {{ fill: {title}; }}")
    return "\n".join(lines)


BASE = """/* Diagrams are inlined SVG so their links stay clickable and CSS can theme
   them. Generated by pytest_hook_atlas.render.css - do not edit by hand. */
.ha-diagram {
  overflow-x: auto;
  margin: 1.2rem 0;
}
.ha-diagram svg {
  max-width: 100%;
  height: auto;
}
.ha-diagram text {
  fill: var(--md-default-fg-color);
}
.ha-diagram .edge path {
  stroke: var(--md-default-fg-color--light);
  fill: none;
}
.ha-diagram .edge polygon {
  fill: var(--md-default-fg-color--light);
  stroke: var(--md-default-fg-color--light);
}
.ha-diagram a {
  cursor: pointer;
}
.ha-diagram a:hover text {
  text-decoration: underline;
}
/* Column headings jump to that phase's detailed diagram, so give the whole
   column a visible affordance rather than only its title. */
.ha-diagram .ha-column:hover path {
  stroke-width: 2.6;
}
.ha-diagram .ha-column a:focus-visible path {
  stroke-width: 2.6;
}
.ha-diagram .ha-column path {
  fill: none;
}

/* The "hide pytest's own plugins" toggle. Added by assets/filter.js only
   when a table actually has something outside pytest to show. */
.ha-filter {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  margin: 0 0 0.6rem;
  font-size: 0.75rem;
  color: var(--md-default-fg-color--light);
  cursor: pointer;
}
.ha-hide-internal .ha-internal {
  display: none;
}
/* separators would otherwise pile up where entries were hidden */
.ha-hide-internal td br {
  display: none;
}
.ha-hide-internal .ha-impl {
  display: block;
}

/* Hook tables. Hook names are long and full of underscores, which browsers
   happily break mid-word into "pytest_cmdline" / "_main". */
.md-typeset table td code,
.md-typeset table th code {
  white-space: nowrap;
}
.md-typeset table td:first-child {
  white-space: nowrap;
}
.md-typeset table td {
  vertical-align: top;
}

/* Version picker. Readers think in pytest versions; the site is organised by
   distinct flows, so picking any version lands on the flow covering it. */
.ha-version-picker {
  display: flex;
  align-items: baseline;
  gap: 0.5rem;
  margin: 0 0 1.2rem;
  font-size: 0.75rem;
}
.ha-version-picker label {
  color: var(--md-default-fg-color--light);
  text-transform: uppercase;
  letter-spacing: 0.06em;
}
.ha-version-picker select {
  font: inherit;
  padding: 0.25rem 0.5rem;
  border-radius: 0.2rem;
  border: 1px solid var(--md-default-fg-color--lighter);
  background: var(--md-default-bg-color);
  color: var(--md-default-fg-color);
}
"""

#: The muted subtitle colour graphviz bakes in as a fill attribute. Overridden
#: per theme because it sits on tinted fills, where the theme's default muted
#: grey drops under 3:1.
MUTED_SELECTOR = '.ha-diagram text[fill="#8a8a8a"]'


def stylesheet() -> str:
    """The full diagram stylesheet, light and dark."""
    return "\n\n".join(
        [
            BASE,
            "/* light theme */",
            f"{MUTED_SELECTOR} {{ fill: #5A5A5A; }}",
            _phase_rules(LIGHT_BACKGROUND, MAX_TINT_LIGHT),
            "/* dark theme: same hues, tinted toward the slate background */",
            f'[data-md-color-scheme="slate"] {MUTED_SELECTOR} {{ fill: #B4B4B4; }}',
            '[data-md-color-scheme="slate"] .ha-diagram .ha-column path { fill: none; }',
            _phase_rules(DARK_BACKGROUND, MAX_TINT_DARK, prefix='[data-md-color-scheme="slate"] '),
            "",
        ]
    )


#: Body text per theme, matching Material's foreground colours.
BODY_TEXT = {"light": "#212121", "dark": "#E3E3E3"}


def theme_settings(theme: str) -> tuple[Rgb, float]:
    """Background and tint ceiling for a named theme."""
    if theme == "dark":
        return DARK_BACKGROUND, MAX_TINT_DARK
    return LIGHT_BACKGROUND, MAX_TINT_LIGHT


def body_text(theme: str) -> str:
    return BODY_TEXT.get(theme, BODY_TEXT["light"])


#: Edge colour per theme. Arrows default to black in Graphviz, which is
#: invisible on the dark background.
EDGE_COLOUR = {"light": "#8A8A8A", "dark": "#9AA0A6"}


def edge_colour(theme: str) -> str:
    return EDGE_COLOUR.get(theme, EDGE_COLOUR["light"])
